name: stonesorders
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  http: any
  flutter_local_notifications:
  meta: any
  platform: any
  expandable_bottom_bar: any
  shared_preferences: any
  flutter_statusbarcolor: any
  flutter_spinkit: any
  flutter_launcher_icons: any
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/images/icon.png"
  image_path_android: "assets/images/icon.png"
  adaptive_icon_background: "assets/images/background.png"
  adaptive_icon_foreground: "assets/images/foreground.png"

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/logo_transparent.png
   - assets/images/logo_square.png
   - assets/images/load.gif
   - images/ideal.gif

  fonts:
    - family: Oswald
      fonts:
        - asset: assets/fonts/Oswald/Oswald-Regular.ttf
          weight: 400
        - asset: assets/fonts/Oswald/Oswald-Bold.ttf
          weight: 700
        - asset: assets/fonts/Oswald/Oswald-Light.ttf
          weight: 300
        - asset: assets/fonts/Oswald/Oswald-Medium.ttf
          weight: 500
        - asset: assets/fonts/Oswald/Oswald-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Oswald/Oswald-ExtraLight.ttf
          weight: 200
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato/Lato-Black.ttf
          weight: 900
        - asset: assets/fonts/Lato/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lato/Lato-Hairline.ttf
          weight: 200
        - asset: assets/fonts/Lato/Lato-Light.ttf
          weight: 300
        - asset: assets/fonts/Lato/Lato-Regular.ttf
          weight: 400
  
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
